#!/bin/bash

#Check root permissions
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root" 
    exit 1
fi

#Check if files exist
input="userlist.txt"

if [ ! -f "$input" ]; then
    echo "$input file not found"
    exit 1
fi

#Change user passwords for standard users
for name in $(cat userlist.txt); do
    echo -n "$name " && passwd $name
done