#!/bin/bash
#Disable unecessary users

#Check root permissions
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root" 
    exit 1
fi

#Check if files exist
input="disable_users.txt"

if [ ! -f "$input" ]; then
    echo "$input file not found"
    exit 1
fi

#Disable unecessary users
for name in $(cat disable_users.txt); do
    echo -n "Setting shell & locking for $name" && usermod -s /sbin/nologin $name && passwd -l $name
done